### ISSUE TITLE
Exception "java.util.NoSuchElementException: No value present"

### ISSUE THREAD

**Issue by hueller** [hueller/weatherstation#1]
```
2015-01-31 04:46:00.899 ERROR ${PID:- } [pool-1-thread-1] --- o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.util.NoSuchElementException: No value present
        at java.util.OptionalDouble.getAsDouble(OptionalDouble.java:118)
        at de.hueller.tinkerforge.weatherstation.web.thingspeak.ThingspeakObserver.getAverageValue(ThingspeakObserver.java:106)
        at de.hueller.tinkerforge.weatherstation.web.thingspeak.ThingspeakObserver.publishWeatherData(ThingspeakObserver.java:52)
        at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by hueller** [comment]
Removed affected class as the TinkSpeak API isn't used anymore.
